site_name: Eclipse Epsilon
nav:
  - Home: index.md
  - Languages:
      - Core language (EOL): 'doc/eol.md'
      - Model connectivity: 'doc/emc.md'
      - Code generation (EGL): 'doc/egl.md'
      - Model validation (EVL): 'doc/evl.md'
      - Model transformation (ETL): 'doc/etl.md'
      - Model comparison (ECL): 'doc/ecl.md'
      - Model merging (EML): 'doc/eml.md'
      - Pattern matching (EPL): 'doc/epl.md'
      - Model Migration (Flock): 'doc/flock.md'
      - Model generation (EMG): 'doc/emg.md'
      - Unit testing (EUnit): 'doc/eunit.md'
  - Tools:
      - Picto: 'doc/picto/index.md'
      - Flexmi: 'doc/flexmi/index.md'
      - Eugenia: 'doc/eugenia/index.md'
      - Exeed: 'doc/exeed/index.md'
      - HUTN: 'doc/hutn.md'
      - Workflow (Ant tasks): 'doc/workflow.md'
  - Articles: 'doc/articles/index.md'
  - Screencasts: 'https://www.youtube.com/epsilondevs'
  - Lectures: 'https://www.youtube.com/playlist?list=PLRwHao6Ue0YUecg7vEUQTrtySIWwrd_mI'
  - Javadoc:
    - Stable: 'https://download.eclipse.org/epsilon/stable/javadoc/'
    - Interim: 'https://download.eclipse.org/epsilon/interim/javadoc/'
  - Community:
      - Who is using Epsilon?:
        - Industry: 'users/index.md'
        - Education: 'users/education.md'
        - Open-source projects: 'users/open-source.md'
      - Who is developing Epsilon?: 'https://projects.eclipse.org/projects/modeling.epsilon/who'
      - Forum: 'https://www.eclipse.org/forums/index.php/f/22/'    
theme: 
  name: material
  custom_dir: custom_theme
  logo: 'assets/images/epsilon-logo-round.png'
  palette:
    primary: 'deep purple'
    accent: 'deep purple'
repo_name: 'Git repository @ Eclipse'
repo_url: 'git://git.eclipse.org/gitroot/epsilon/org.eclipse.epsilon.git'
markdown_extensions:
  - admonition
  - footnotes
  - codehilite:
      guess_lang: false
      linenums: true
  - toc:
      permalink: true
plugins:
    - search
    - redirects:
        redirect_maps:
            'doc/articles/emfatic.md': 'https://www.eclipse.org/emfatic'
            'doc/articles/eugenia-gmf-tutorial/index.md': 'doc/eugenia/index.md'
            'doc/articles/flexmi/index.md': 'doc/flexmi/index.md'
            'doc/articles/picto/index.md': 'doc/picto/index.md'
            'doc/articles/exeed-reference/index.md': 'doc/exeed/index.md'

copyright: 'Copyright © Eclipse Foundation, Inc. All Rights Reserved.'
extra_css:
  - 'stylesheets/extra.css'
