name: Test local Playground

on:
  push:
    branches: [ "main" ]
    paths:
      - mkdocs/docs/playground/**
      - mkdocs/docs/serve-no-livereload.sh
      - .github/workflows/local-playground-test.yml
  pull_request:
    branches: [ "main" ]
    paths:
      - mkdocs/docs/playground/**
      - mkdocs/docs/serve-no-livereload.sh
      - .github/workflows/local-playground-test.yml
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js 18.x
      uses: actions/setup-node@v4
      with:
        node-version: 18.x
    - uses: actions/setup-python@v5
      with:
        python-version: '3.13'
        cache: 'pip'
    - name: Run Cypress tests on local Playground
      run: |
        cd mkdocs/docs/playground
        ./run-cypress-local.sh
    - name: Upload Cypress screenshots
      uses: actions/upload-artifact@v4
      if: '!cancelled()'
      with:
        name: cypress-screenshots
        path: mkdocs/docs/playground/cypress/screenshots