name: Deploy playground-monaco to GitHub Pages

on:
  push:
    branches:
      - playground-monaco
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: playground-monaco

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v2
        with:
          path: mkdocs/docs/playground

  deploy-pages:
    needs: deploy
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2
